#!/bin/bash

#######################################
#  Script name: 324_purge_nvidia_driver
#  Created on: Aug 26, 2026
#  Author: Jim Moersfelder
#  Purpose: To uninstall any pre-installed nvidia driver
#  Synopsis:
#  Notes:  I got it from old ways of removing NVIDIA scripts.
#######################################

echo "purge Nvidia drivers install..."

# Exits out of the program if hte computer doesn't have an NVIDIA card
if [ ! "`/usr/bin/lspci | /bin/grep NVIDIA`" ]; then
  echo "No NVIDIA cards found. Exiting without install."
  exit
fi

# Remove all instances of nouveau or cuda/nvidia existing already
apt-get -y purge xserver-xorg-video-nouveau
apt-get -y purge libdrm-nouveau
apt-get autoremove -y

#cp blacklist-nouveau.conf /etc/modprobe.d/
#echo " blacklist nouveau" >> /etc/modprobe.d/blacklist.conf
echo "blacklist nouveau" >> /etc/modprobe.d/blacklist.conf
