#!/bin/bash
#######################################
#  Script name: 330_repositories 
#  Created on: 10-17-2013  
#  Author: Jim Moersfelder      
#  Purpose: Set up repositories for dnf (previously yum)     
#  Synopsis: Adds the Fedora, VirtualBox, Chrome, Adobe, and RPMFusion
#            repositories and then updates    
#  Notes: dnf update may take some time as it updates all the packages that have already beed installed       
#  History: 6/25/15  Jarred Stein - Rewrote F20 script to be compatible with F22
#                     (replacing yum with dnf) 
#                     Also deleted commented out/ deprecated yum installs
#           7/23/15  Bill Otwell - Verified changed, added header
#           7/24/15  Jim Moersfelder - removed "-q" options from dnf commands
#	    10/5/15  Jarred Stein - commented out dnf repolist because it would time out during ks
#      	    02/16/17 Jarred Stein - added Fish shell repo per INC0391598
# 	    06/28/17 Samuel Tseng - Updated for U16.04.
#######################################

echo "updating apt and adding ubuntu-standard"
apt-get -y update
apt-get install ubuntu-standard -y
apt-get -y update



echo "Adding repositories for apt-get"


#Fish shell repo
apt-add-repository ppa:fish-shell/release-3 -y


#Codelite Repository
#From: https://wiki.codelite.org/pmwiki.php/Main/Repositories
##apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
##apt-add-repository -y "deb http://repos.codelite.org/ubuntu/ $(lsb_release -sc) universe"


#Rstudio dependencies repository
#echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list
#apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9


#Python2.3 repository
#add-apt-repository ppa:fkrull/deadsnakes -y
# REMOVED by Jim on 180112 because it was failing
#gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DB82666C vi /etc/apt/sources.list deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main deb-src 


#Virtualbox repository
#echo "deb http://download.virtualbox.org/virtualbox/debian xenial contrib" >> /etc/apt/sources.list
#wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
#wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -


#MySQL repository
# Jim comment all this out for Ubuntu 22.04, he thought
# it would all work with Ubuntu repo
#apt-key adv --keyserver keys.gnupg.net --recv-keys 5072E1F5
#sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu/ xenial mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
# for mysql
#apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8C718D3B5072E1F5



#Atom repository
####wget -q https://packagecloud.io/AtomEditor/atom/gpgkey -O- | apt-key add -
####sh -c 'add-apt-repository -y "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"'
#add-apt-repository ppa:webupd8team/atom -y

# Update everything
apt-get -y update


# Display repolist for ks log
#dnf repolist

echo "\nDone!"
