#!/bin/bash

#######################################
#  Script name: 360_pycharn-edu
#  Created on: January 11, 2024
#  Author: Jim Moersfelder
#  Purpose: To install pycharm-educational
#  Synopsis:
#  Notes:  course  ECS171 INC1814960
#                                            
#          
#######################################

echo "Doing pycharm-educational..."

snap install pycharm-educational --classic

echo "DONE with pycharm-educational..."
