#!/bin/bash

#######################################
#  Script name: 360_apptainer
#  Created on: December 20, 2022
#  Author: Jim Moersfelder
#  Purpose: To install apptainer on the computers in the CSIF
#  Synopsis:
#  Notes:  Hoa Nguyen wanted it. INC1532850
#          COE-IT suggested https://apptainer.org/ because it is 
#          used on HPC.  It has a rootless part.  
#  History: Jim Moersfelder updated it Aug. 27, 2026 changed to apt
#           https://apptainer.org/docs/admin/main/installation.html#install-from-pre-built-packages
#          
#######################################

echo "Doing apptainer..."

# apt install
apt update
apt install -y software-properties-common

add-apt-repository -y ppa:apptainer/ppa
apt update
apt install -y apptainer


#cd /tmp
# wget https://github.com/apptainer/apptainer/releases/download/v1.1.4/apptainer_1.1.4_amd64.deb
#apt-get install -y ./apptainer_1.1.4_amd64.deb

#wget https://github.com/apptainer/apptainer/releases/download/v1.5.3/apptainer_1.5.3_amd64.deb
#apt-get install -y ./apptainer_1.5.3_amd64.deb
echo "DONE with apptainer..."
