#!/bin/bash

#######################################
#  Script name: 360_vscode
#  Created on: September 14, 2024
#  Author: Jim Moersfelder
#  Purpose: Installs vscode
#  Synopsis:
#  Notes:  Sam King wanted it for ecs50 INC2062122
#         Here is the page I followed:
#          https://code.visualstudio.com/docs/setup/linux
#######################################

echo "Doing vscode..."
echo "code code/add-microsoft-repo boolean true" | debconf-set-selections

cd /tmp

apt-get install wget gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | tee /etc/apt/sources.list.d/vscode.list > /dev/null
rm -f packages.microsoft.gpg

apt install apt-transport-https
apt update
apt install code # or code-insiders

