#!/bin/bash

#######################################
#  Script name:  360_gcc15
#  Created on:  12/29/26
#  Author:      Jim Moersfelder 
#  Purpose: Install gcc15 on ubuntu 22.04                
#  Synopsis:     
#  Notes: RITM0143011
#  History:      
#
#############################################

echo "Installing GCC 15..."

apt-get -y update
apt-get -y upgrade
apt -y install build-essential libgmp-dev libmpfr-dev libmpc-dev flex bison texinfo

cd /tmp
wget https://ftp.gnu.org/gnu/gcc/gcc-15.1.0/gcc-15.1.0.tar.xz
tar -xf gcc-15.1.0.tar.xz
cd gcc-15.1.0
mkdir build
cd build

../configure --prefix=/opt/gcc-15 --disable-multilib --enable-languages=c,c++
make -j$(nproc)
make install
/opt/gcc-15/bin/gcc --version
