#!/bin/bash

#######################################
#  Script name: 360_CUDA
#  Created on: September 19, 2022
#  Author: Jim Moersfelder
#  Purpose: To install CUDA 11, tensorflow and NVIDIA drivers
#  Synopsis:
#  Notes:  Student wanted it for ecs171-Machine learning class INC1306659
#         Here is the page I followed:
#          https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_110
#         I documented it here:
#            https://docs.google.com/document/d/1kLgGHhtXyUYEm46H2t4iOJHF8t_SzLQCDnEofMBEXgU/edit?usp=sharing
#         In support_files/CUDA11 I ran these wgets

#          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
#          wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
#         wget https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/libnvinfer7_7.1.3-1+cuda11.0_amd64.deb
#######################################

echo "Doing graphics..."

if [ ! "`/usr/bin/lspci | /bin/grep NVIDIA`" ]; then
  echo "No NVIDIA cards found. Exiting without install."
  exit
fi

apt install -y build-essential dkms linux-headers-$(uname -r)

#rm /etc/apt/sources.list.d/cuda*
#apt remove -y nvidia-*
#apt remove -y cuda-*

apt -y update
apt -y upgrade

#apt install -y cuda
apt install -y cuda-toolkit



#cd /tmp
# Doesn't do anything
#wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
#dpkg -i ./cuda-keyring_1.1-1_all.deb

#wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-archive-keyring.gpg
#mv cuda-archive-keyring.gpg /usr/share/keyrings/cuda-archive-keyring.gpg
#echo "deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /" \
#    | tee /etc/apt/sources.list.d/cuda-ubuntu2204-x86_64.list

# apt update

#apt update
#apt-get -y install cuda cuda-drivers
#apt-get -y install nvidia-cuda-toolkit
#apt -y install linux-headers-$(uname -r)
#apt -y install nvidia-open
#apt -y install cuda-toolkit
#apt -y install nvidia-gds
#apt -y install cuda-compat
