#!/bin/bash

#######################################
#  Script name: 360_vscode
#  Created on: September 14, 2024
#  Author: Jim Moersfelder
#  Purpose: Installs vscode
#  Synopsis:
#  Notes:  Sam King wanted it for ecs50 INC2062122
#         Here is the page I followed:
#          https://code.visualstudio.com/docs/setup/linux
#######################################

echo "Doing vscode..."
# this turns off interactive mode
echo "code code/add-microsoft-repo boolean true" | sudo debconf-set-selections

apt -y install ./code_1.134.0-1787078834_amd64.deb





#echo "code code/add-microsoft-repo boolean true" | debconf-set-selections


#cd /tmp
# old way
#apt-get update
#apt-get -y install wget gpg curl
#wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
#install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
#echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | tee /etc/apt/sources.list.d/vscode.list > /dev/null
#rm -f packages.microsoft.gpg

# 26.04 way
#apt update && apt install -y curl gpg test-utils
#curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
#apt-get install wget gpg
#wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft.gpg > /dev/null
#wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
#install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
#rm -f packages.microsoft.gpg
#echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list
#apt -y modernize-sources
#apt update &&  apt install code


#22.04 way
#apt install apt-transport-https
#apt update
#apt install code # or code-insiders

