#!/bin/bash

#######################################
#  Script name: 750_50-render
#  Created on: May 24, 2024
#  Author: Jim Moersfelder
#  Purpose: Joel Porquet-Lupine wanted it installed for his class
#  Synopsis:
#  Notes:  INC1943108
#######################################
#
#


echo "Doing 750_render..."
echo "SUBSYSTEM==\"drm\", KERNEL==\"renderD\*\", GROUP=\"render\", MODE=\"0666\"" > /etc/udev/rules.d/99-render.rules
echo "Done 750_render..."
